// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class APIResource {
    "gvr": string;
    "kind": string;
    "namespaced": boolean;

    /** Creates a new APIResource instance. */
    constructor($$source: Partial<APIResource> = {}) {
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("namespaced" in $$source)) {
            this["namespaced"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIResource instance from a string or object.
     */
    static createFrom($$source: any = {}): APIResource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIResource($$parsedSource as Partial<APIResource>);
    }
}

export class APIServerHealth {
    "livez": HealthStatus;
    "readyz": HealthStatus;
    "healthz": HealthStatus;

    /** Creates a new APIServerHealth instance. */
    constructor($$source: Partial<APIServerHealth> = {}) {
        if (!("livez" in $$source)) {
            this["livez"] = HealthStatus.$zero;
        }
        if (!("readyz" in $$source)) {
            this["readyz"] = HealthStatus.$zero;
        }
        if (!("healthz" in $$source)) {
            this["healthz"] = HealthStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIServerHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): APIServerHealth {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIServerHealth($$parsedSource as Partial<APIServerHealth>);
    }
}

export class ClusterHealth {
    "apiServer": APIServerHealth;
    "components": ComponentHealth[];
    "nodes": NodeSummary;
    "checkedAt": time$0.Time;

    /** Creates a new ClusterHealth instance. */
    constructor($$source: Partial<ClusterHealth> = {}) {
        if (!("apiServer" in $$source)) {
            this["apiServer"] = (new APIServerHealth());
        }
        if (!("components" in $$source)) {
            this["components"] = [];
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = (new NodeSummary());
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterHealth {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apiServer" in $$parsedSource) {
            $$parsedSource["apiServer"] = $$createField0_0($$parsedSource["apiServer"]);
        }
        if ("components" in $$parsedSource) {
            $$parsedSource["components"] = $$createField1_0($$parsedSource["components"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField2_0($$parsedSource["nodes"]);
        }
        return new ClusterHealth($$parsedSource as Partial<ClusterHealth>);
    }
}

export class ComponentHealth {
    "name": string;
    "status": HealthStatus;
    "message": string;

    /** Creates a new ComponentHealth instance. */
    constructor($$source: Partial<ComponentHealth> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = HealthStatus.$zero;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): ComponentHealth {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComponentHealth($$parsedSource as Partial<ComponentHealth>);
    }
}

export enum ConnectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StatusDisconnected = 0,
    StatusConnecting = 1,
    StatusConnected = 2,
    StatusError = 3,
};

export enum HealthStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    HealthOK = 0,
    HealthDegraded = 1,
    HealthUnknown = 2,
};

export class KubeContext {
    "name": string;
    "cluster": string;
    "user": string;
    "namespace": string;
    "status": ConnectionStatus;
    "serverVersion": string;
    "provider": string;

    /** Creates a new KubeContext instance. */
    constructor($$source: Partial<KubeContext> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("serverVersion" in $$source)) {
            this["serverVersion"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeContext instance from a string or object.
     */
    static createFrom($$source: any = {}): KubeContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeContext($$parsedSource as Partial<KubeContext>);
    }
}

export class Manager {

    /** Creates a new Manager instance. */
    constructor($$source: Partial<Manager> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     */
    static createFrom($$source: any = {}): Manager {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager($$parsedSource as Partial<Manager>);
    }
}

export class NodeSummary {
    "total": number;
    "ready": number;
    "notReady": number;
    "schedulingDisabled": number;
    "permissionDenied": boolean;

    /** Creates a new NodeSummary instance. */
    constructor($$source: Partial<NodeSummary> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("ready" in $$source)) {
            this["ready"] = 0;
        }
        if (!("notReady" in $$source)) {
            this["notReady"] = 0;
        }
        if (!("schedulingDisabled" in $$source)) {
            this["schedulingDisabled"] = 0;
        }
        if (!("permissionDenied" in $$source)) {
            this["permissionDenied"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeSummary($$parsedSource as Partial<NodeSummary>);
    }
}

// Private type creation functions
const $$createType0 = APIServerHealth.createFrom;
const $$createType1 = ComponentHealth.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = NodeSummary.createFrom;
