// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class APIResource {
    /**
     * Creates a new APIResource instance.
     * @param {Partial<APIResource>} [$$source = {}] - The source object to create the APIResource.
     */
    constructor($$source = {}) {
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("namespaced" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["namespaced"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIResource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIResource}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIResource(/** @type {Partial<APIResource>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const ConnectionStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    StatusDisconnected: 0,
    StatusConnecting: 1,
    StatusConnected: 2,
    StatusError: 3,
};

export class KubeContext {
    /**
     * Creates a new KubeContext instance.
     * @param {Partial<KubeContext>} [$$source = {}] - The source object to create the KubeContext.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("cluster" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cluster"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {ConnectionStatus}
             */
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("serverVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverVersion"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeContext instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KubeContext}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeContext(/** @type {Partial<KubeContext>} */($$parsedSource));
    }
}

export class Manager {
    /**
     * Creates a new Manager instance.
     * @param {Partial<Manager>} [$$source = {}] - The source object to create the Manager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager(/** @type {Partial<Manager>} */($$parsedSource));
    }
}
