// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class APIResource {
    "gvr": string;
    "kind": string;
    "namespaced": boolean;

    /** Creates a new APIResource instance. */
    constructor($$source: Partial<APIResource> = {}) {
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("namespaced" in $$source)) {
            this["namespaced"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIResource instance from a string or object.
     */
    static createFrom($$source: any = {}): APIResource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIResource($$parsedSource as Partial<APIResource>);
    }
}

export enum ConnectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StatusDisconnected = 0,
    StatusConnecting = 1,
    StatusConnected = 2,
    StatusError = 3,
};

export class KubeContext {
    "name": string;
    "cluster": string;
    "user": string;
    "namespace": string;
    "status": ConnectionStatus;
    "serverVersion": string;
    "provider": string;

    /** Creates a new KubeContext instance. */
    constructor($$source: Partial<KubeContext> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("serverVersion" in $$source)) {
            this["serverVersion"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeContext instance from a string or object.
     */
    static createFrom($$source: any = {}): KubeContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeContext($$parsedSource as Partial<KubeContext>);
    }
}

export class Manager {

    /** Creates a new Manager instance. */
    constructor($$source: Partial<Manager> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     */
    static createFrom($$source: any = {}): Manager {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager($$parsedSource as Partial<Manager>);
    }
}
