// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class APIResource {
    /**
     * Creates a new APIResource instance.
     * @param {Partial<APIResource>} [$$source = {}] - The source object to create the APIResource.
     */
    constructor($$source = {}) {
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("namespaced" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["namespaced"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIResource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIResource}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIResource(/** @type {Partial<APIResource>} */($$parsedSource));
    }
}

export class APIServerHealth {
    /**
     * Creates a new APIServerHealth instance.
     * @param {Partial<APIServerHealth>} [$$source = {}] - The source object to create the APIServerHealth.
     */
    constructor($$source = {}) {
        if (!("livez" in $$source)) {
            /**
             * @member
             * @type {HealthStatus}
             */
            this["livez"] = HealthStatus.$zero;
        }
        if (!("readyz" in $$source)) {
            /**
             * @member
             * @type {HealthStatus}
             */
            this["readyz"] = HealthStatus.$zero;
        }
        if (!("healthz" in $$source)) {
            /**
             * @member
             * @type {HealthStatus}
             */
            this["healthz"] = HealthStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIServerHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIServerHealth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIServerHealth(/** @type {Partial<APIServerHealth>} */($$parsedSource));
    }
}

export class ClusterHealth {
    /**
     * Creates a new ClusterHealth instance.
     * @param {Partial<ClusterHealth>} [$$source = {}] - The source object to create the ClusterHealth.
     */
    constructor($$source = {}) {
        if (!("apiServer" in $$source)) {
            /**
             * @member
             * @type {APIServerHealth}
             */
            this["apiServer"] = (new APIServerHealth());
        }
        if (!("components" in $$source)) {
            /**
             * @member
             * @type {ComponentHealth[]}
             */
            this["components"] = [];
        }
        if (!("nodes" in $$source)) {
            /**
             * @member
             * @type {NodeSummary}
             */
            this["nodes"] = (new NodeSummary());
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["checkedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClusterHealth}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apiServer" in $$parsedSource) {
            $$parsedSource["apiServer"] = $$createField0_0($$parsedSource["apiServer"]);
        }
        if ("components" in $$parsedSource) {
            $$parsedSource["components"] = $$createField1_0($$parsedSource["components"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField2_0($$parsedSource["nodes"]);
        }
        return new ClusterHealth(/** @type {Partial<ClusterHealth>} */($$parsedSource));
    }
}

export class ComponentHealth {
    /**
     * Creates a new ComponentHealth instance.
     * @param {Partial<ComponentHealth>} [$$source = {}] - The source object to create the ComponentHealth.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {HealthStatus}
             */
            this["status"] = HealthStatus.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComponentHealth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComponentHealth(/** @type {Partial<ComponentHealth>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const ConnectionStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    StatusDisconnected: 0,
    StatusConnecting: 1,
    StatusConnected: 2,
    StatusError: 3,
};

/**
 * @readonly
 * @enum {number}
 */
export const HealthStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    HealthOK: 0,
    HealthDegraded: 1,
    HealthUnknown: 2,
};

export class KubeContext {
    /**
     * Creates a new KubeContext instance.
     * @param {Partial<KubeContext>} [$$source = {}] - The source object to create the KubeContext.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("cluster" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cluster"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {ConnectionStatus}
             */
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("serverVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverVersion"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeContext instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KubeContext}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeContext(/** @type {Partial<KubeContext>} */($$parsedSource));
    }
}

export class Manager {
    /**
     * Creates a new Manager instance.
     * @param {Partial<Manager>} [$$source = {}] - The source object to create the Manager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager(/** @type {Partial<Manager>} */($$parsedSource));
    }
}

export class NodeSummary {
    /**
     * Creates a new NodeSummary instance.
     * @param {Partial<NodeSummary>} [$$source = {}] - The source object to create the NodeSummary.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ready"] = 0;
        }
        if (!("notReady" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["notReady"] = 0;
        }
        if (!("schedulingDisabled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schedulingDisabled"] = 0;
        }
        if (!("permissionDenied" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["permissionDenied"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NodeSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeSummary(/** @type {Partial<NodeSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = APIServerHealth.createFrom;
const $$createType1 = ComponentHealth.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = NodeSummary.createFrom;
