// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ClusterPrefs {
    "readOnly"?: boolean | null;
    "compactRows"?: boolean | null;
    "accentColor"?: string | null;
    "displayName"?: string | null;
    "metrics"?: MetricsConfig | null;
    "columnPrefs"?: { [_ in string]?: GVRColumnPrefs | null };
    "favoriteNamespaces"?: string[];
    "savedFilters"?: { [_ in string]?: SavedFilter[] };

    /** Creates a new ClusterPrefs instance. */
    constructor($$source: Partial<ClusterPrefs> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterPrefs instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterPrefs {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField4_0($$parsedSource["metrics"]);
        }
        if ("columnPrefs" in $$parsedSource) {
            $$parsedSource["columnPrefs"] = $$createField5_0($$parsedSource["columnPrefs"]);
        }
        if ("favoriteNamespaces" in $$parsedSource) {
            $$parsedSource["favoriteNamespaces"] = $$createField6_0($$parsedSource["favoriteNamespaces"]);
        }
        if ("savedFilters" in $$parsedSource) {
            $$parsedSource["savedFilters"] = $$createField7_0($$parsedSource["savedFilters"]);
        }
        return new ClusterPrefs($$parsedSource as Partial<ClusterPrefs>);
    }
}

export class ColumnSettings {
    "width"?: number;

    /** Creates a new ColumnSettings instance. */
    constructor($$source: Partial<ColumnSettings> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnSettings($$parsedSource as Partial<ColumnSettings>);
    }
}

export class Config {
    "theme": string;
    "kubeconfigPaths": string[];
    "terminalWebGL": boolean;
    "disabledPlugins"?: string[];
    "insecureRegistries"?: string[];
    "insecureSkipTLSVerify"?: boolean;
    "metrics"?: { [_ in string]?: MetricsConfig | null };
    "columnPrefs"?: { [_ in string]?: GVRColumnPrefs | null };
    "compactRows"?: boolean;
    "readOnly"?: boolean;
    "portForwards"?: { [_ in string]?: SavedPortForward[] };
    "clusters"?: { [_ in string]?: ClusterPrefs | null };
    "keybindings"?: { [_ in string]?: string };
    "savedFilters"?: { [_ in string]?: SavedFilter[] };
    "startupBehavior"?: string;
    "startupCluster"?: string;
    "accentColor"?: string;
    "fontSize"?: number;
    "contextualAutocomplete"?: boolean | null;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("kubeconfigPaths" in $$source)) {
            this["kubeconfigPaths"] = [];
        }
        if (!("terminalWebGL" in $$source)) {
            this["terminalWebGL"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField1_0 = $$createType5;
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType5;
        const $$createField6_0 = $$createType9;
        const $$createField7_0 = $$createType4;
        const $$createField10_0 = $$createType12;
        const $$createField11_0 = $$createType15;
        const $$createField12_0 = $$createType16;
        const $$createField13_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kubeconfigPaths" in $$parsedSource) {
            $$parsedSource["kubeconfigPaths"] = $$createField1_0($$parsedSource["kubeconfigPaths"]);
        }
        if ("disabledPlugins" in $$parsedSource) {
            $$parsedSource["disabledPlugins"] = $$createField3_0($$parsedSource["disabledPlugins"]);
        }
        if ("insecureRegistries" in $$parsedSource) {
            $$parsedSource["insecureRegistries"] = $$createField4_0($$parsedSource["insecureRegistries"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField6_0($$parsedSource["metrics"]);
        }
        if ("columnPrefs" in $$parsedSource) {
            $$parsedSource["columnPrefs"] = $$createField7_0($$parsedSource["columnPrefs"]);
        }
        if ("portForwards" in $$parsedSource) {
            $$parsedSource["portForwards"] = $$createField10_0($$parsedSource["portForwards"]);
        }
        if ("clusters" in $$parsedSource) {
            $$parsedSource["clusters"] = $$createField11_0($$parsedSource["clusters"]);
        }
        if ("keybindings" in $$parsedSource) {
            $$parsedSource["keybindings"] = $$createField12_0($$parsedSource["keybindings"]);
        }
        if ("savedFilters" in $$parsedSource) {
            $$parsedSource["savedFilters"] = $$createField13_0($$parsedSource["savedFilters"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class GVRColumnPrefs {
    "columns": { [_ in string]?: ColumnSettings };
    "order": string[];
    "sort"?: SortPrefs | null;

    /** Creates a new GVRColumnPrefs instance. */
    constructor($$source: Partial<GVRColumnPrefs> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = {};
        }
        if (!("order" in $$source)) {
            this["order"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GVRColumnPrefs instance from a string or object.
     */
    static createFrom($$source: any = {}): GVRColumnPrefs {
        const $$createField0_0 = $$createType18;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("order" in $$parsedSource) {
            $$parsedSource["order"] = $$createField1_0($$parsedSource["order"]);
        }
        if ("sort" in $$parsedSource) {
            $$parsedSource["sort"] = $$createField2_0($$parsedSource["sort"]);
        }
        return new GVRColumnPrefs($$parsedSource as Partial<GVRColumnPrefs>);
    }
}

export class MetricsConfig {
    "prometheusUrl"?: string;

    /** Creates a new MetricsConfig instance. */
    constructor($$source: Partial<MetricsConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MetricsConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricsConfig($$parsedSource as Partial<MetricsConfig>);
    }
}

export class ResolvedPrefs {
    "theme": string;
    "accentColor": string;
    "fontSize": number;
    "compactRows": boolean;
    "readOnly": boolean;
    "terminalWebGL": boolean;
    "metrics"?: MetricsConfig | null;
    "columnPrefs"?: { [_ in string]?: GVRColumnPrefs | null };
    "favoriteNamespaces"?: string[];
    "keybindings"?: { [_ in string]?: string };
    "savedFilters"?: { [_ in string]?: SavedFilter[] };
    "contextualAutocomplete": boolean;

    /** Creates a new ResolvedPrefs instance. */
    constructor($$source: Partial<ResolvedPrefs> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("accentColor" in $$source)) {
            this["accentColor"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("compactRows" in $$source)) {
            this["compactRows"] = false;
        }
        if (!("readOnly" in $$source)) {
            this["readOnly"] = false;
        }
        if (!("terminalWebGL" in $$source)) {
            this["terminalWebGL"] = false;
        }
        if (!("contextualAutocomplete" in $$source)) {
            this["contextualAutocomplete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedPrefs instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolvedPrefs {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType5;
        const $$createField9_0 = $$createType16;
        const $$createField10_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField6_0($$parsedSource["metrics"]);
        }
        if ("columnPrefs" in $$parsedSource) {
            $$parsedSource["columnPrefs"] = $$createField7_0($$parsedSource["columnPrefs"]);
        }
        if ("favoriteNamespaces" in $$parsedSource) {
            $$parsedSource["favoriteNamespaces"] = $$createField8_0($$parsedSource["favoriteNamespaces"]);
        }
        if ("keybindings" in $$parsedSource) {
            $$parsedSource["keybindings"] = $$createField9_0($$parsedSource["keybindings"]);
        }
        if ("savedFilters" in $$parsedSource) {
            $$parsedSource["savedFilters"] = $$createField10_0($$parsedSource["savedFilters"]);
        }
        return new ResolvedPrefs($$parsedSource as Partial<ResolvedPrefs>);
    }
}

export class SavedFilter {
    "name": string;
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };
    "search"?: string;

    /** Creates a new SavedFilter instance. */
    constructor($$source: Partial<SavedFilter> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedFilter {
        const $$createField1_0 = $$createType16;
        const $$createField2_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField1_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField2_0($$parsedSource["annotations"]);
        }
        return new SavedFilter($$parsedSource as Partial<SavedFilter>);
    }
}

export class SavedPortForward {
    "id": string;
    "namespace": string;
    "resource": string;
    "targetKind": string;
    "targetName": string;
    "targetGVR"?: string;
    "localPort": number;
    "remotePort": number;
    "enabled": boolean;

    /** Creates a new SavedPortForward instance. */
    constructor($$source: Partial<SavedPortForward> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("targetKind" in $$source)) {
            this["targetKind"] = "";
        }
        if (!("targetName" in $$source)) {
            this["targetName"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedPortForward instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedPortForward {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedPortForward($$parsedSource as Partial<SavedPortForward>);
    }
}

export class SortPrefs {
    "column": string;
    "direction": string;

    /** Creates a new SortPrefs instance. */
    constructor($$source: Partial<SortPrefs> = {}) {
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SortPrefs instance from a string or object.
     */
    static createFrom($$source: any = {}): SortPrefs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SortPrefs($$parsedSource as Partial<SortPrefs>);
    }
}

// Private type creation functions
const $$createType0 = MetricsConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = GVRColumnPrefs.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = SavedFilter.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = $Create.Map($Create.Any, $$createType1);
const $$createType10 = SavedPortForward.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Map($Create.Any, $$createType11);
const $$createType13 = ClusterPrefs.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Map($Create.Any, $$createType14);
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
const $$createType17 = ColumnSettings.createFrom;
const $$createType18 = $Create.Map($Create.Any, $$createType17);
const $$createType19 = SortPrefs.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
