// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    "theme": string;
    "kubeconfigPaths": string[];
    "terminalWebGL": boolean;
    "disabledPlugins"?: string[];
    "insecureRegistries"?: string[];
    "insecureSkipTLSVerify"?: boolean;
    "metrics"?: { [_ in string]?: MetricsConfig | null };

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("kubeconfigPaths" in $$source)) {
            this["kubeconfigPaths"] = [];
        }
        if (!("terminalWebGL" in $$source)) {
            this["terminalWebGL"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kubeconfigPaths" in $$parsedSource) {
            $$parsedSource["kubeconfigPaths"] = $$createField1_0($$parsedSource["kubeconfigPaths"]);
        }
        if ("disabledPlugins" in $$parsedSource) {
            $$parsedSource["disabledPlugins"] = $$createField3_0($$parsedSource["disabledPlugins"]);
        }
        if ("insecureRegistries" in $$parsedSource) {
            $$parsedSource["insecureRegistries"] = $$createField4_0($$parsedSource["insecureRegistries"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField6_0($$parsedSource["metrics"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class MetricsConfig {
    "prometheusUrl"?: string;

    /** Creates a new MetricsConfig instance. */
    constructor($$source: Partial<MetricsConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MetricsConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricsConfig($$parsedSource as Partial<MetricsConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = MetricsConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
