// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("kubeconfigPaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["kubeconfigPaths"] = [];
        }
        if (!("terminalWebGL" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["terminalWebGL"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["disabledPlugins"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["insecureRegistries"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["insecureSkipTLSVerify"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kubeconfigPaths" in $$parsedSource) {
            $$parsedSource["kubeconfigPaths"] = $$createField1_0($$parsedSource["kubeconfigPaths"]);
        }
        if ("disabledPlugins" in $$parsedSource) {
            $$parsedSource["disabledPlugins"] = $$createField3_0($$parsedSource["disabledPlugins"]);
        }
        if ("insecureRegistries" in $$parsedSource) {
            $$parsedSource["insecureRegistries"] = $$createField4_0($$parsedSource["insecureRegistries"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
