// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ColumnSettings {
    /**
     * Creates a new ColumnSettings instance.
     * @param {Partial<ColumnSettings>} [$$source = {}] - The source object to create the ColumnSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnSettings(/** @type {Partial<ColumnSettings>} */($$parsedSource));
    }
}

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("kubeconfigPaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["kubeconfigPaths"] = [];
        }
        if (!("terminalWebGL" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["terminalWebGL"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["disabledPlugins"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["insecureRegistries"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["insecureSkipTLSVerify"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: MetricsConfig | null } | undefined}
             */
            this["metrics"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: GVRColumnPrefs | null } | undefined}
             */
            this["columnPrefs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["compactRows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["readOnly"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: SavedPortForward[] } | undefined}
             */
            this["portForwards"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType6;
        const $$createField10_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kubeconfigPaths" in $$parsedSource) {
            $$parsedSource["kubeconfigPaths"] = $$createField1_0($$parsedSource["kubeconfigPaths"]);
        }
        if ("disabledPlugins" in $$parsedSource) {
            $$parsedSource["disabledPlugins"] = $$createField3_0($$parsedSource["disabledPlugins"]);
        }
        if ("insecureRegistries" in $$parsedSource) {
            $$parsedSource["insecureRegistries"] = $$createField4_0($$parsedSource["insecureRegistries"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField6_0($$parsedSource["metrics"]);
        }
        if ("columnPrefs" in $$parsedSource) {
            $$parsedSource["columnPrefs"] = $$createField7_0($$parsedSource["columnPrefs"]);
        }
        if ("portForwards" in $$parsedSource) {
            $$parsedSource["portForwards"] = $$createField10_0($$parsedSource["portForwards"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class GVRColumnPrefs {
    /**
     * Creates a new GVRColumnPrefs instance.
     * @param {Partial<GVRColumnPrefs>} [$$source = {}] - The source object to create the GVRColumnPrefs.
     */
    constructor($$source = {}) {
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: ColumnSettings }}
             */
            this["columns"] = {};
        }
        if (!("order" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["order"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SortPrefs | null | undefined}
             */
            this["sort"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GVRColumnPrefs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GVRColumnPrefs}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("order" in $$parsedSource) {
            $$parsedSource["order"] = $$createField1_0($$parsedSource["order"]);
        }
        if ("sort" in $$parsedSource) {
            $$parsedSource["sort"] = $$createField2_0($$parsedSource["sort"]);
        }
        return new GVRColumnPrefs(/** @type {Partial<GVRColumnPrefs>} */($$parsedSource));
    }
}

export class MetricsConfig {
    /**
     * Creates a new MetricsConfig instance.
     * @param {Partial<MetricsConfig>} [$$source = {}] - The source object to create the MetricsConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["prometheusUrl"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MetricsConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricsConfig(/** @type {Partial<MetricsConfig>} */($$parsedSource));
    }
}

export class SavedPortForward {
    /**
     * Creates a new SavedPortForward instance.
     * @param {Partial<SavedPortForward>} [$$source = {}] - The source object to create the SavedPortForward.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("resource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resource"] = "";
        }
        if (!("targetKind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetKind"] = "";
        }
        if (!("targetName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetGVR"] = undefined;
        }
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("remotePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remotePort"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedPortForward instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedPortForward}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedPortForward(/** @type {Partial<SavedPortForward>} */($$parsedSource));
    }
}

export class SortPrefs {
    /**
     * Creates a new SortPrefs instance.
     * @param {Partial<SortPrefs>} [$$source = {}] - The source object to create the SortPrefs.
     */
    constructor($$source = {}) {
        if (!("column" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["direction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SortPrefs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SortPrefs}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SortPrefs(/** @type {Partial<SortPrefs>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = MetricsConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = GVRColumnPrefs.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = SavedPortForward.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = ColumnSettings.createFrom;
const $$createType11 = $Create.Map($Create.Any, $$createType10);
const $$createType12 = SortPrefs.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
