// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Action {
    /**
     * Creates a new Action instance.
     * @param {Partial<Action>} [$$source = {}] - The source object to create the Action.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["disabledWhen"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["disabledReason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Action}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Action(/** @type {Partial<Action>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const AlignType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AlignLeft: "left",
    AlignRight: "right",
    AlignCenter: "center",
};

export class Column {
    /**
     * Creates a new Column instance.
     * @param {Partial<Column>} [$$source = {}] - The source object to create the Column.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("expr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expr"] = "";
        }
        if (!("renderType" in $$source)) {
            /**
             * @member
             * @type {RenderType}
             */
            this["renderType"] = RenderType.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AlignType | undefined}
             */
            this["align"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["hidden"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Column}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Column(/** @type {Partial<Column>} */($$parsedSource));
    }
}

export class Descriptor {
    /**
     * Creates a new Descriptor instance.
     * @param {Partial<Descriptor>} [$$source = {}] - The source object to create the Descriptor.
     */
    constructor($$source = {}) {
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("resource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resource"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["kind"] = undefined;
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {Column[]}
             */
            this["columns"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {OverviewField[] | undefined}
             */
            this["overviewFields"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["detailPanels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Action[] | undefined}
             */
            this["actions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["clusterScoped"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Descriptor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Descriptor}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField4_0($$parsedSource["columns"]);
        }
        if ("overviewFields" in $$parsedSource) {
            $$parsedSource["overviewFields"] = $$createField5_0($$parsedSource["overviewFields"]);
        }
        if ("detailPanels" in $$parsedSource) {
            $$parsedSource["detailPanels"] = $$createField6_0($$parsedSource["detailPanels"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField7_0($$parsedSource["actions"]);
        }
        return new Descriptor(/** @type {Partial<Descriptor>} */($$parsedSource));
    }
}

export class EnricherRegistry {
    /**
     * Creates a new EnricherRegistry instance.
     * @param {Partial<EnricherRegistry>} [$$source = {}] - The source object to create the EnricherRegistry.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnricherRegistry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnricherRegistry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnricherRegistry(/** @type {Partial<EnricherRegistry>} */($$parsedSource));
    }
}

export class OverviewField {
    /**
     * Creates a new OverviewField instance.
     * @param {Partial<OverviewField>} [$$source = {}] - The source object to create the OverviewField.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("expr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expr"] = "";
        }
        if (!("renderType" in $$source)) {
            /**
             * @member
             * @type {RenderType}
             */
            this["renderType"] = RenderType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverviewField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OverviewField}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OverviewField(/** @type {Partial<OverviewField>} */($$parsedSource));
    }
}

export class Registry {
    /**
     * Creates a new Registry instance.
     * @param {Partial<Registry>} [$$source = {}] - The source object to create the Registry.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Registry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Registry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Registry(/** @type {Partial<Registry>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const RenderType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RenderText: "text",
    RenderBadge: "badge",
    RenderAge: "age",
    RenderProgress: "progress",
};

export class ResourceEngine {
    /**
     * Creates a new ResourceEngine instance.
     * @param {Partial<ResourceEngine>} [$$source = {}] - The source object to create the ResourceEngine.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceEngine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResourceEngine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceEngine(/** @type {Partial<ResourceEngine>} */($$parsedSource));
    }
}

/**
 * Template is a named YAML scaffold for creating a Kubernetes resource.
 */
export class Template {
    /**
     * Creates a new Template instance.
     * @param {Partial<Template>} [$$source = {}] - The source object to create the Template.
     */
    constructor($$source = {}) {
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Template instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Template}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Template(/** @type {Partial<Template>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Column.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = OverviewField.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = Action.createFrom;
const $$createType6 = $Create.Array($$createType5);
