// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Action {
    "name": string;
    "label": string;
    "disabledWhen"?: string;
    "disabledReason"?: string;

    /** Creates a new Action instance. */
    constructor($$source: Partial<Action> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     */
    static createFrom($$source: any = {}): Action {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Action($$parsedSource as Partial<Action>);
    }
}

export class Column {
    "name": string;
    "expr": string;
    "renderType": RenderType;
    "width"?: number;

    /** Creates a new Column instance. */
    constructor($$source: Partial<Column> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("expr" in $$source)) {
            this["expr"] = "";
        }
        if (!("renderType" in $$source)) {
            this["renderType"] = RenderType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     */
    static createFrom($$source: any = {}): Column {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Column($$parsedSource as Partial<Column>);
    }
}

export class Descriptor {
    "group": string;
    "version": string;
    "resource": string;
    "kind"?: string;
    "columns": Column[];
    "overviewFields"?: OverviewField[];
    "detailPanels"?: string[];
    "actions"?: Action[];
    "clusterScoped"?: boolean;

    /** Creates a new Descriptor instance. */
    constructor($$source: Partial<Descriptor> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Descriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): Descriptor {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField4_0($$parsedSource["columns"]);
        }
        if ("overviewFields" in $$parsedSource) {
            $$parsedSource["overviewFields"] = $$createField5_0($$parsedSource["overviewFields"]);
        }
        if ("detailPanels" in $$parsedSource) {
            $$parsedSource["detailPanels"] = $$createField6_0($$parsedSource["detailPanels"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField7_0($$parsedSource["actions"]);
        }
        return new Descriptor($$parsedSource as Partial<Descriptor>);
    }
}

export class EnricherRegistry {

    /** Creates a new EnricherRegistry instance. */
    constructor($$source: Partial<EnricherRegistry> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnricherRegistry instance from a string or object.
     */
    static createFrom($$source: any = {}): EnricherRegistry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnricherRegistry($$parsedSource as Partial<EnricherRegistry>);
    }
}

export class OverviewField {
    "label": string;
    "expr": string;
    "renderType": RenderType;

    /** Creates a new OverviewField instance. */
    constructor($$source: Partial<OverviewField> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("expr" in $$source)) {
            this["expr"] = "";
        }
        if (!("renderType" in $$source)) {
            this["renderType"] = RenderType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverviewField instance from a string or object.
     */
    static createFrom($$source: any = {}): OverviewField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OverviewField($$parsedSource as Partial<OverviewField>);
    }
}

export class Registry {

    /** Creates a new Registry instance. */
    constructor($$source: Partial<Registry> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Registry instance from a string or object.
     */
    static createFrom($$source: any = {}): Registry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Registry($$parsedSource as Partial<Registry>);
    }
}

export enum RenderType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RenderText = "text",
    RenderBadge = "badge",
    RenderAge = "age",
    RenderProgress = "progress",
};

export class ResourceEngine {

    /** Creates a new ResourceEngine instance. */
    constructor($$source: Partial<ResourceEngine> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceEngine instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceEngine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceEngine($$parsedSource as Partial<ResourceEngine>);
    }
}

// Private type creation functions
const $$createType0 = Column.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = OverviewField.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = Action.createFrom;
const $$createType6 = $Create.Array($$createType5);
