// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    CommandEntry,
    ContextMenuEntry,
    DetailTabEntry,
    HeaderWidgetEntry,
    ListColumnEntry,
    OverviewFieldEntry,
    PermsSummary,
    PluginInfo,
    ResourcePerm,
    SidebarEntry,
    StatusBarEntry
} from "./models.js";
