/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Frontend PluginContext interface — constructed from manifest permissions
 */
export interface PluginContext {
  cluster: {
    name: string;
    version: string;
  };
  namespace: string;
  k8s?: K8SContext;
  logs?: LogsContext;
  exec?: ExecContext;
  storage?: StorageContext;
  [k: string]: unknown;
}
/**
 * Only present if permissions.resources declared
 */
export interface K8SContext {
  list(gvr: string, ns?: string): Promise<unknown[]>;
  get(gvr: string, ns: string, name: string): Promise<unknown>;
  watch(gvr: string, ns: string, callback: (event: unknown) => void): () => void;
  [k: string]: unknown;
}
/**
 * Only present if permissions.logs: true
 */
export interface LogsContext {
  stream(pod: string, ns: string, container: string, opts?: { follow?: boolean; previous?: boolean; tailLines?: number }): Promise<unknown>;
  stop(streamID: string): Promise<unknown>;
  [k: string]: unknown;
}
/**
 * Only present if permissions.exec: true
 */
export interface ExecContext {
  open(pod: string, ns: string, container: string, shell?: string): Promise<unknown>;
  close(sessionID: string): Promise<unknown>;
  [k: string]: unknown;
}
/**
 * Only present if permissions.storage: true
 */
export interface StorageContext {
  get(key: string): Promise<string | null>;
  set(key: string, value: string): Promise<void>;
  delete(key: string): Promise<void>;
  [k: string]: unknown;
}
