/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Frontend PluginContext interface — constructed from manifest permissions
 */
export interface PluginContext {
  cluster: {
    name: string;
    version: string;
  };
  namespace: string;
  k8s?: K8SContext;
  logs?: LogsContext;
  exec?: ExecContext;
  storage?: StorageContext;
  [k: string]: unknown;
}
/**
 * Only present if permissions.resources declared
 */
export interface K8SContext {
  /** List resources by GVR and optional namespace */
  list: (gvr: string, ns?: string) => Promise<unknown[]>;
  /** Get a single resource by GVR, namespace, and name */
  get: (gvr: string, ns: string, name: string) => Promise<unknown>;
  /** Subscribe to resource changes, returns unsubscribe function */
  watch: (gvr: string, ns: string, callback: (event: unknown) => void) => () => void;
  [k: string]: unknown;
}
/**
 * Only present if permissions.logs: true
 */
export interface LogsContext {
  /** Start a log stream for a container */
  stream: (pod: string, ns: string, container: string, opts?: { follow?: boolean; previous?: boolean; tailLines?: number }) => Promise<string>;
  /** Stop a log stream */
  stop: (streamID: string) => Promise<void>;
  [k: string]: unknown;
}
/**
 * Only present if permissions.exec: true
 */
export interface ExecContext {
  /** Open an exec session for a container */
  open: (pod: string, ns: string, container: string, shell?: string) => Promise<string>;
  [k: string]: unknown;
}
/**
 * Only present if permissions.storage: true
 */
export interface StorageContext {
  /** Read a value from plugin-local storage */
  get: (key: string) => Promise<unknown>;
  /** Write a value to plugin-local storage */
  set: (key: string, value: unknown) => Promise<void>;
  /** Delete a key from plugin-local storage */
  delete: (key: string) => Promise<void>;
  [k: string]: unknown;
}
