/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Frontend PluginContext interface — constructed from manifest permissions
 */
export interface PluginContext {
  cluster: {
    name: string;
    version: string;
  };
  namespace: string;
  k8s?: K8SContext;
  logs?: LogsContext;
  exec?: ExecContext;
  storage?: StorageContext;
  [k: string]: unknown;
}
/**
 * Only present if permissions.resources declared
 */
export interface K8SContext {
  /**
   * List resources by GVR and optional namespace
   */
  list: {
    [k: string]: unknown;
  };
  /**
   * Get a single resource by GVR, namespace, and name
   */
  get: {
    [k: string]: unknown;
  };
  /**
   * Subscribe to resource changes, returns unsubscribe function
   */
  watch: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Only present if permissions.logs: true
 */
export interface LogsContext {
  /**
   * Start a log stream for a container
   */
  stream: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Only present if permissions.exec: true
 */
export interface ExecContext {
  /**
   * Open an exec session for a container
   */
  open: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Only present if permissions.storage: true
 */
export interface StorageContext {
  /**
   * Read a value from plugin-local storage
   */
  get: {
    [k: string]: unknown;
  };
  /**
   * Write a value to plugin-local storage
   */
  set: {
    [k: string]: unknown;
  };
  /**
   * Delete a key from plugin-local storage
   */
  delete: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
