/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Klados plugin manifest schema (v1)
 */
export interface PluginManifest {
  schemaVersion: 1;
  /**
   * Unique plugin identifier (lowercase, hyphens)
   */
  name: string;
  /**
   * Plugin version (semver)
   */
  version: string;
  displayName: string;
  description?: string;
  /**
   * Minimum klados host version required (semver)
   */
  minHostVersion: string;
  permissions?: Permissions;
  extensions?: Extensions;
}
export interface Permissions {
  resources?: ResourcePermission[];
  logs?: boolean;
  exec?: boolean;
  storage?: boolean;
  events?: boolean;
  wasi?: WasiPermissions;
}
export interface ResourcePermission {
  group: string;
  version: string;
  resource: string;
  /**
   * @minItems 1
   */
  verbs: [
    "list" | "get" | "watch" | "create" | "update" | "delete",
    ...("list" | "get" | "watch" | "create" | "update" | "delete")[]
  ];
}
export interface WasiPermissions {
  clock?: boolean;
  filesystem?: boolean;
  network?: boolean;
  env?: boolean;
}
export interface Extensions {
  /**
   * Relative paths to descriptor YAML files
   */
  descriptors?: string[];
  enrichers?: EnricherConfig;
  sidebar?: SidebarEntry[];
  detailTabs?: DetailTab[];
  commands?: Command[];
  overviewFields?: ComponentRef[];
  listColumns?: ComponentRef[];
  contextMenu?: ComponentRef[];
  headerWidgets?: ComponentRef[];
  statusBar?: ComponentRef[];
  /**
   * PromQL query templates per GVR, rendered as additional charts in the metrics tab
   */
  metrics?: MetricTemplateGroup[];
  settings?: SettingsDeclaration;
}
export interface EnricherConfig {
  /**
   * Relative path to the Wasm module
   */
  wasm: string;
  /**
   * GVR strings this enricher handles (dot-separated format)
   */
  gvrs: string[];
}
export interface SidebarEntry {
  category: string;
  label: string;
  gvr: string;
  icon?: string;
}
export interface DetailTab {
  gvr: string;
  id: string;
  label: string;
  /**
   * Relative path to the Svelte component JS bundle
   */
  component: string;
}
export interface Command {
  id: string;
  label: string;
  icon?: string;
  /**
   * Relative path to Svelte component JS bundle. If set, mounts UI component instead of calling Wasm.
   */
  component?: string;
}
export interface ComponentRef {
  id: string;
  label: string;
  /**
   * GVR filter (omit for global slots)
   */
  gvr?: string;
  /**
   * Relative path to the Svelte component JS bundle
   */
  component: string;
}
export interface MetricTemplateGroup {
  /**
   * GVR this group of queries applies to (dot-separated format)
   */
  gvr: string;
  /**
   * @minItems 1
   */
  queries: [MetricTemplateQuery, ...MetricTemplateQuery[]];
}
export interface MetricTemplateQuery {
  /**
   * Display name for the chart
   */
  name: string;
  /**
   * PromQL template with {{var}} placeholders
   */
  query: string;
  /**
   * Unit label (e.g. req/s, bytes, cores)
   */
  unit: string;
}
export interface SettingsDeclaration {
  /**
   * JSON Schema (draft 2020-12) defining the plugin's settings. Must be type: object with properties.
   */
  schema: {
    [k: string]: unknown;
  };
}
