// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"

type Command struct {
	// Relative path to Svelte component JS bundle. If set, mounts UI component
	// instead of calling Wasm.
	Component *string `json:"component,omitempty"`

	// Icon corresponds to the JSON schema field "icon".
	Icon *string `json:"icon,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Command) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Command: required")
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in Command: required")
	}
	type Plain Command
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Command(plain)
	return nil
}

type ComponentRef struct {
	// Relative path to the Svelte component JS bundle
	Component string `json:"component"`

	// GVR filter (omit for global slots)
	Gvr *string `json:"gvr,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ComponentRef) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["component"]; raw != nil && !ok {
		return fmt.Errorf("field component in ComponentRef: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ComponentRef: required")
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in ComponentRef: required")
	}
	type Plain ComponentRef
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ComponentRef(plain)
	return nil
}

type DetailTab struct {
	// Relative path to the Svelte component JS bundle
	Component string `json:"component"`

	// Gvr corresponds to the JSON schema field "gvr".
	Gvr string `json:"gvr"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DetailTab) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["component"]; raw != nil && !ok {
		return fmt.Errorf("field component in DetailTab: required")
	}
	if _, ok := raw["gvr"]; raw != nil && !ok {
		return fmt.Errorf("field gvr in DetailTab: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in DetailTab: required")
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in DetailTab: required")
	}
	type Plain DetailTab
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DetailTab(plain)
	return nil
}

type EnricherConfig struct {
	// GVR strings this enricher handles (dot-separated format)
	Gvrs []string `json:"gvrs"`

	// Relative path to the Wasm module
	Wasm string `json:"wasm"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnricherConfig) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["gvrs"]; raw != nil && !ok {
		return fmt.Errorf("field gvrs in EnricherConfig: required")
	}
	if _, ok := raw["wasm"]; raw != nil && !ok {
		return fmt.Errorf("field wasm in EnricherConfig: required")
	}
	type Plain EnricherConfig
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = EnricherConfig(plain)
	return nil
}

type Extensions struct {
	// Commands corresponds to the JSON schema field "commands".
	Commands []Command `json:"commands,omitempty"`

	// ContextMenu corresponds to the JSON schema field "contextMenu".
	ContextMenu []ComponentRef `json:"contextMenu,omitempty"`

	// Relative paths to descriptor YAML files
	Descriptors []string `json:"descriptors,omitempty"`

	// DetailTabs corresponds to the JSON schema field "detailTabs".
	DetailTabs []DetailTab `json:"detailTabs,omitempty"`

	// Enrichers corresponds to the JSON schema field "enrichers".
	Enrichers *EnricherConfig `json:"enrichers,omitempty"`

	// HeaderWidgets corresponds to the JSON schema field "headerWidgets".
	HeaderWidgets []ComponentRef `json:"headerWidgets,omitempty"`

	// ListColumns corresponds to the JSON schema field "listColumns".
	ListColumns []ComponentRef `json:"listColumns,omitempty"`

	// PromQL query templates per GVR, rendered as additional charts in the metrics
	// tab
	Metrics []MetricTemplateGroup `json:"metrics,omitempty"`

	// OverviewFields corresponds to the JSON schema field "overviewFields".
	OverviewFields []ComponentRef `json:"overviewFields,omitempty"`

	// Sidebar corresponds to the JSON schema field "sidebar".
	Sidebar []SidebarEntry `json:"sidebar,omitempty"`

	// StatusBar corresponds to the JSON schema field "statusBar".
	StatusBar []ComponentRef `json:"statusBar,omitempty"`
}

// Klados plugin manifest schema (v1)
type ManifestV1Json struct {
	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty"`

	// DisplayName corresponds to the JSON schema field "displayName".
	DisplayName string `json:"displayName"`

	// Extensions corresponds to the JSON schema field "extensions".
	Extensions *Extensions `json:"extensions,omitempty"`

	// Minimum klados host version required (semver)
	MinHostVersion string `json:"minHostVersion"`

	// Unique plugin identifier (lowercase, hyphens)
	Name string `json:"name"`

	// Permissions corresponds to the JSON schema field "permissions".
	Permissions *Permissions `json:"permissions,omitempty"`

	// SchemaVersion corresponds to the JSON schema field "schemaVersion".
	SchemaVersion int `json:"schemaVersion"`

	// Plugin version (semver)
	Version string `json:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ManifestV1Json) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["displayName"]; raw != nil && !ok {
		return fmt.Errorf("field displayName in ManifestV1Json: required")
	}
	if _, ok := raw["minHostVersion"]; raw != nil && !ok {
		return fmt.Errorf("field minHostVersion in ManifestV1Json: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ManifestV1Json: required")
	}
	if _, ok := raw["schemaVersion"]; raw != nil && !ok {
		return fmt.Errorf("field schemaVersion in ManifestV1Json: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in ManifestV1Json: required")
	}
	type Plain ManifestV1Json
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z0-9][a-z0-9-]*[a-z0-9]$`, string(plain.Name)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Name", `^[a-z0-9][a-z0-9-]*[a-z0-9]$`)
	}
	if plain.SchemaVersion != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "schemaVersion", 1)
	}
	*j = ManifestV1Json(plain)
	return nil
}

type MetricTemplateGroup struct {
	// GVR this group of queries applies to (dot-separated format)
	Gvr string `json:"gvr"`

	// Queries corresponds to the JSON schema field "queries".
	Queries []MetricTemplateQuery `json:"queries"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MetricTemplateGroup) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["gvr"]; raw != nil && !ok {
		return fmt.Errorf("field gvr in MetricTemplateGroup: required")
	}
	if _, ok := raw["queries"]; raw != nil && !ok {
		return fmt.Errorf("field queries in MetricTemplateGroup: required")
	}
	type Plain MetricTemplateGroup
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Queries != nil && len(plain.Queries) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "queries", 1)
	}
	*j = MetricTemplateGroup(plain)
	return nil
}

type MetricTemplateQuery struct {
	// Display name for the chart
	Name string `json:"name"`

	// PromQL template with {{var}} placeholders
	Query string `json:"query"`

	// Unit label (e.g. req/s, bytes, cores)
	Unit string `json:"unit"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MetricTemplateQuery) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in MetricTemplateQuery: required")
	}
	if _, ok := raw["query"]; raw != nil && !ok {
		return fmt.Errorf("field query in MetricTemplateQuery: required")
	}
	if _, ok := raw["unit"]; raw != nil && !ok {
		return fmt.Errorf("field unit in MetricTemplateQuery: required")
	}
	type Plain MetricTemplateQuery
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MetricTemplateQuery(plain)
	return nil
}

type Permissions struct {
	// Events corresponds to the JSON schema field "events".
	Events *bool `json:"events,omitempty"`

	// Exec corresponds to the JSON schema field "exec".
	Exec *bool `json:"exec,omitempty"`

	// Logs corresponds to the JSON schema field "logs".
	Logs *bool `json:"logs,omitempty"`

	// Resources corresponds to the JSON schema field "resources".
	Resources []ResourcePermission `json:"resources,omitempty"`

	// Storage corresponds to the JSON schema field "storage".
	Storage *bool `json:"storage,omitempty"`

	// Wasi corresponds to the JSON schema field "wasi".
	Wasi *WasiPermissions `json:"wasi,omitempty"`
}

type ResourcePermission struct {
	// Group corresponds to the JSON schema field "group".
	Group string `json:"group"`

	// Resource corresponds to the JSON schema field "resource".
	Resource string `json:"resource"`

	// Verbs corresponds to the JSON schema field "verbs".
	Verbs []ResourcePermissionVerbsElem `json:"verbs"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version"`
}

type ResourcePermissionVerbsElem string

const ResourcePermissionVerbsElemCreate ResourcePermissionVerbsElem = "create"
const ResourcePermissionVerbsElemDelete ResourcePermissionVerbsElem = "delete"
const ResourcePermissionVerbsElemGet ResourcePermissionVerbsElem = "get"
const ResourcePermissionVerbsElemList ResourcePermissionVerbsElem = "list"
const ResourcePermissionVerbsElemUpdate ResourcePermissionVerbsElem = "update"
const ResourcePermissionVerbsElemWatch ResourcePermissionVerbsElem = "watch"

var enumValues_ResourcePermissionVerbsElem = []interface{}{
	"list",
	"get",
	"watch",
	"create",
	"update",
	"delete",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResourcePermissionVerbsElem) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResourcePermissionVerbsElem {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ResourcePermissionVerbsElem, v)
	}
	*j = ResourcePermissionVerbsElem(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResourcePermission) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["group"]; raw != nil && !ok {
		return fmt.Errorf("field group in ResourcePermission: required")
	}
	if _, ok := raw["resource"]; raw != nil && !ok {
		return fmt.Errorf("field resource in ResourcePermission: required")
	}
	if _, ok := raw["verbs"]; raw != nil && !ok {
		return fmt.Errorf("field verbs in ResourcePermission: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in ResourcePermission: required")
	}
	type Plain ResourcePermission
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Verbs != nil && len(plain.Verbs) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "verbs", 1)
	}
	*j = ResourcePermission(plain)
	return nil
}

type SidebarEntry struct {
	// Category corresponds to the JSON schema field "category".
	Category string `json:"category"`

	// Gvr corresponds to the JSON schema field "gvr".
	Gvr string `json:"gvr"`

	// Icon corresponds to the JSON schema field "icon".
	Icon *string `json:"icon,omitempty"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SidebarEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["category"]; raw != nil && !ok {
		return fmt.Errorf("field category in SidebarEntry: required")
	}
	if _, ok := raw["gvr"]; raw != nil && !ok {
		return fmt.Errorf("field gvr in SidebarEntry: required")
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in SidebarEntry: required")
	}
	type Plain SidebarEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SidebarEntry(plain)
	return nil
}

type WasiPermissions struct {
	// Clock corresponds to the JSON schema field "clock".
	Clock *bool `json:"clock,omitempty"`

	// Env corresponds to the JSON schema field "env".
	Env *bool `json:"env,omitempty"`

	// Filesystem corresponds to the JSON schema field "filesystem".
	Filesystem *bool `json:"filesystem,omitempty"`

	// Network corresponds to the JSON schema field "network".
	Network *bool `json:"network,omitempty"`
}
