// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cluster$0 from "../cluster/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as exec$0 from "../exec/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logs$0 from "../logs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as portforward$0 from "../portforward/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as streaming$0 from "../streaming/models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function BrowseKubeconfigFile() {
    return $Call.ByID(3812723218);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function BrowsePluginFile() {
    return $Call.ByID(3044813074);
}

/**
 * @returns {$CancellablePromise<cluster$0.Manager | null>}
 */
export function ClusterManager() {
    return $Call.ByID(1018019196).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function Config() {
    return $Call.ByID(2025854175).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<context$0.Context>}
 */
export function Ctx() {
    return $Call.ByID(532202374);
}

/**
 * @returns {$CancellablePromise<exec$0.Manager | null>}
 */
export function ExecManager() {
    return $Call.ByID(181455691).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} connCtx
 * @returns {$CancellablePromise<cluster$0.ClusterHealth>}
 */
export function GetClusterHealth(connCtx) {
    return $Call.ByID(3203745337, connCtx).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<session$0.Session | null>}
 */
export function GetSession() {
    return $Call.ByID(3130725049).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<streaming$0.StreamingConfig>}
 */
export function GetStreamingConfig() {
    return $Call.ByID(3228718747).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} level
 * @param {string} message
 * @param {string} detail
 * @returns {$CancellablePromise<void>}
 */
export function LogFrontend(level, message, detail) {
    return $Call.ByID(4188773513, level, message, detail);
}

/**
 * @returns {$CancellablePromise<logs$0.Streamer | null>}
 */
export function LogStreamer() {
    return $Call.ByID(2788254666).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<portforward$0.Manager | null>}
 */
export function PortForwardManager() {
    return $Call.ByID(3269944274).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function RegisterPluginsDir(dir) {
    return $Call.ByID(1267291503, dir);
}

/**
 * @param {session$0.TabState[]} openTabs
 * @param {number} activeTab
 * @param {boolean} sidebarCollapsed
 * @param {number} terminalFontSize
 * @returns {$CancellablePromise<void>}
 */
export function SaveUIState(openTabs, activeTab, sidebarCollapsed, terminalFontSize) {
    return $Call.ByID(1357217799, openTabs, activeTab, sidebarCollapsed, terminalFontSize);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetReadOnly(enabled) {
    return $Call.ByID(1908353457, enabled);
}

// Private type creation functions
const $$createType0 = cluster$0.Manager.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.Config.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = exec$0.Manager.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = cluster$0.ClusterHealth.createFrom;
const $$createType7 = session$0.Session.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = streaming$0.StreamingConfig.createFrom;
const $$createType10 = logs$0.Streamer.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = portforward$0.Manager.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
