// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cluster$0 from "../cluster/models.js";

/**
 * @param {string} path
 * @returns {$CancellablePromise<cluster$0.KubeContext[]>}
 */
export function AddKubeconfigPath(path) {
    return $Call.ByID(3424427683, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<void>}
 */
export function Connect(contextName) {
    return $Call.ByID(2564928362, contextName);
}

/**
 * @param {string} contextName
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateNamespace(contextName, name) {
    return $Call.ByID(3190336079, contextName, name);
}

/**
 * @param {string} contextName
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNamespace(contextName, name) {
    return $Call.ByID(3734241090, contextName, name);
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect(contextName) {
    return $Call.ByID(3294121038, contextName);
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveNamespace(contextName) {
    return $Call.ByID(3979351489, contextName);
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<cluster$0.ConnectionStatus>}
 */
export function GetStatus(contextName) {
    return $Call.ByID(3771597842, contextName);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<cluster$0.KubeContext[]>}
 */
export function ImportKubeconfigContent(content) {
    return $Call.ByID(3631082547, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<cluster$0.KubeContext[]>}
 */
export function ListContexts() {
    return $Call.ByID(1707520196).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<string[]>}
 */
export function ListNamespaces(contextName) {
    return $Call.ByID(1900087040, contextName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @returns {$CancellablePromise<void>}
 */
export function SwitchNamespace(contextName, $namespace) {
    return $Call.ByID(4142974063, contextName, $namespace);
}

// Private type creation functions
const $$createType0 = cluster$0.KubeContext.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
