// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(3349102092).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetInsecureSkipTLSVerify(): $CancellablePromise<boolean> {
    return $Call.ByID(3151101633);
}

export function GetTerminalWebGL(): $CancellablePromise<boolean> {
    return $Call.ByID(1404868855);
}

export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(3339073715);
}

export function SetInsecureSkipTLSVerify(skip: boolean): $CancellablePromise<void> {
    return $Call.ByID(2704534973, skip);
}

export function SetTerminalWebGL(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(95260947, enabled);
}

export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(2227324903, theme);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
