// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(3349102092).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetInsecureSkipTLSVerify() {
    return $Call.ByID(3151101633);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetTerminalWebGL() {
    return $Call.ByID(1404868855);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(3339073715);
}

/**
 * @param {boolean} skip
 * @returns {$CancellablePromise<void>}
 */
export function SetInsecureSkipTLSVerify(skip) {
    return $Call.ByID(2704534973, skip);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetTerminalWebGL(enabled) {
    return $Call.ByID(95260947, enabled);
}

/**
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(theme) {
    return $Call.ByID(2227324903, theme);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
