// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * @param {string} ctxName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteClusterPrefs(ctxName) {
    return $Call.ByID(991424445, ctxName);
}

/**
 * @param {string} gvr
 * @returns {$CancellablePromise<void>}
 */
export function DeleteColumnPrefs(gvr) {
    return $Call.ByID(4114770319, gvr);
}

/**
 * @param {string} ctxName
 * @returns {$CancellablePromise<config$0.ClusterPrefs | null>}
 */
export function GetClusterPrefs(ctxName) {
    return $Call.ByID(3907658678, ctxName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} gvr
 * @returns {$CancellablePromise<config$0.GVRColumnPrefs | null>}
 */
export function GetColumnPrefs(gvr) {
    return $Call.ByID(2172831658, gvr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetCompactRows() {
    return $Call.ByID(2422269906);
}

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(3349102092).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetInsecureSkipTLSVerify() {
    return $Call.ByID(3151101633);
}

/**
 * @param {string} ctxName
 * @returns {$CancellablePromise<config$0.ResolvedPrefs>}
 */
export function GetResolvedPrefs(ctxName) {
    return $Call.ByID(3736726204, ctxName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} gvr
 * @returns {$CancellablePromise<config$0.SavedFilter[]>}
 */
export function GetSavedFilters(gvr) {
    return $Call.ByID(2202435792, gvr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetTerminalWebGL() {
    return $Call.ByID(1404868855);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(3339073715);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResetKeybindings() {
    return $Call.ByID(1736506518);
}

/**
 * @param {string} color
 * @returns {$CancellablePromise<void>}
 */
export function SetAccentColor(color) {
    return $Call.ByID(2723403775, color);
}

/**
 * @param {string} ctxName
 * @param {config$0.ClusterPrefs | null} prefs
 * @returns {$CancellablePromise<void>}
 */
export function SetClusterPrefs(ctxName, prefs) {
    return $Call.ByID(3679024642, ctxName, prefs);
}

/**
 * @param {string} ctxName
 * @param {string} gvr
 * @param {config$0.SavedFilter[]} filters
 * @returns {$CancellablePromise<void>}
 */
export function SetClusterSavedFilters(ctxName, gvr, filters) {
    return $Call.ByID(3426066010, ctxName, gvr, filters);
}

/**
 * @param {string} gvr
 * @param {config$0.GVRColumnPrefs | null} prefs
 * @returns {$CancellablePromise<void>}
 */
export function SetColumnPrefs(gvr, prefs) {
    return $Call.ByID(2017648422, gvr, prefs);
}

/**
 * @param {boolean} compact
 * @returns {$CancellablePromise<void>}
 */
export function SetCompactRows(compact) {
    return $Call.ByID(407269070, compact);
}

/**
 * @param {number} size
 * @returns {$CancellablePromise<void>}
 */
export function SetFontSize(size) {
    return $Call.ByID(2949195894, size);
}

/**
 * @param {boolean} skip
 * @returns {$CancellablePromise<void>}
 */
export function SetInsecureSkipTLSVerify(skip) {
    return $Call.ByID(2704534973, skip);
}

/**
 * @param {string} actionID
 * @param {string} keys
 * @returns {$CancellablePromise<void>}
 */
export function SetKeybinding(actionID, keys) {
    return $Call.ByID(644345986, actionID, keys);
}

/**
 * @param {string} gvr
 * @param {config$0.SavedFilter[]} filters
 * @returns {$CancellablePromise<void>}
 */
export function SetSavedFilters(gvr, filters) {
    return $Call.ByID(3820903460, gvr, filters);
}

/**
 * @param {string} behavior
 * @param {string} cluster
 * @returns {$CancellablePromise<void>}
 */
export function SetStartupBehavior(behavior, cluster) {
    return $Call.ByID(3615998021, behavior, cluster);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetTerminalWebGL(enabled) {
    return $Call.ByID(95260947, enabled);
}

/**
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(theme) {
    return $Call.ByID(2227324903, theme);
}

// Private type creation functions
const $$createType0 = config$0.ClusterPrefs.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.GVRColumnPrefs.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = config$0.Config.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = config$0.ResolvedPrefs.createFrom;
const $$createType7 = config$0.SavedFilter.createFrom;
const $$createType8 = $Create.Array($$createType7);
