// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} contextName
 * @param {string} nodeName
 * @returns {$CancellablePromise<void>}
 */
export function CancelDrain(contextName, nodeName) {
    return $Call.ByID(575867988, contextName, nodeName);
}

/**
 * Cordon marks the node as unschedulable.
 * @param {string} contextName
 * @param {string} nodeName
 * @returns {$CancellablePromise<void>}
 */
export function CordonNode(contextName, nodeName) {
    return $Call.ByID(2446363129, contextName, nodeName);
}

/**
 * @param {string} contextName
 * @param {string} nodeName
 * @returns {$CancellablePromise<boolean>}
 */
export function IsActive(contextName, nodeName) {
    return $Call.ByID(2487772726, contextName, nodeName);
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<string[]>}
 */
export function ListActive(contextName) {
    return $Call.ByID(1665099622, contextName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} nodeName
 * @returns {$CancellablePromise<void>}
 */
export function StartDrain(contextName, nodeName) {
    return $Call.ByID(474780626, contextName, nodeName);
}

/**
 * Uncordon marks the node as schedulable.
 * @param {string} contextName
 * @param {string} nodeName
 * @returns {$CancellablePromise<void>}
 */
export function UncordonNode(contextName, nodeName) {
    return $Call.ByID(1142118830, contextName, nodeName);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
