// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseExecSession(sessionID) {
    return $Call.ByID(234028266, sessionID);
}

/**
 * @param {string} ctxName
 * @param {string} ns
 * @param {string} podName
 * @param {string} container
 * @param {string} shell
 * @returns {$CancellablePromise<string>}
 */
export function OpenExecSession(ctxName, ns, podName, container, shell) {
    return $Call.ByID(1841438172, ctxName, ns, podName, container, shell);
}
