// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HelmService exposes Helm verbs and lazy detail-tab fetches over Wails RPC.
 * It owns the Helm backend, actions wrapper, and per-release SAR-gated calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as helm$0 from "../helm/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanupTestPods deletes pods labelled as Helm test hooks for the given
 * release. Both the "helm.sh/hook=test-success" and "helm.sh/hook=test" labels
 * are recognised; the annotation form is not labelled and is not selectable
 * server-side, so we filter client-side by annotation as a fallback.
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @returns {$CancellablePromise<void>}
 */
export function CleanupTestPods(contextName, $namespace, releaseName) {
    return $Call.ByID(3206390368, contextName, $namespace, releaseName);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @param {number} $from
 * @param {number} to
 * @returns {$CancellablePromise<helm$0.RevisionDiff>}
 */
export function DiffRevisions(contextName, $namespace, releaseName, $from, to) {
    return $Call.ByID(2689002639, contextName, $namespace, releaseName, $from, to).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @param {number} revision
 * @returns {$CancellablePromise<void>}
 */
export function ForceDeleteReleaseSecret(contextName, $namespace, releaseName, revision) {
    return $Call.ByID(1874861993, contextName, $namespace, releaseName, revision);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @returns {$CancellablePromise<helm$0.Revision[]>}
 */
export function GetHistory(contextName, $namespace, releaseName) {
    return $Call.ByID(448915676, contextName, $namespace, releaseName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @param {number} revision
 * @returns {$CancellablePromise<helm$0.Hook[]>}
 */
export function GetHooks(contextName, $namespace, releaseName, revision) {
    return $Call.ByID(3337667848, contextName, $namespace, releaseName, revision).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @param {number} revision
 * @returns {$CancellablePromise<string>}
 */
export function GetManifest(contextName, $namespace, releaseName, revision) {
    return $Call.ByID(1931393849, contextName, $namespace, releaseName, revision);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @param {number} revision
 * @returns {$CancellablePromise<string>}
 */
export function GetNotes(contextName, $namespace, releaseName, revision) {
    return $Call.ByID(3306052593, contextName, $namespace, releaseName, revision);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @param {boolean} scanAll
 * @returns {$CancellablePromise<helm$0.OwnedRef[]>}
 */
export function GetOwnedResources(contextName, $namespace, releaseName, scanAll) {
    return $Call.ByID(3286556010, contextName, $namespace, releaseName, scanAll).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetReleasePermissions returns the per-verb RBAC allow flags for the
 * (context, namespace, release) triple. Errors from individual SAR calls
 * degrade gracefully: the specific verb is reported false but no error is
 * surfaced to the caller.
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @returns {$CancellablePromise<$models.HelmPermissions>}
 */
export function GetReleasePermissions(contextName, $namespace, releaseName) {
    return $Call.ByID(1933921127, contextName, $namespace, releaseName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @param {boolean} computed
 * @param {number} revision
 * @returns {$CancellablePromise<string>}
 */
export function GetValues(contextName, $namespace, releaseName, computed, revision) {
    return $Call.ByID(4076722466, contextName, $namespace, releaseName, computed, revision);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @param {number} revision
 * @param {$models.HelmRollbackOpts} opts
 * @returns {$CancellablePromise<void>}
 */
export function Rollback(contextName, $namespace, releaseName, revision, opts) {
    return $Call.ByID(1703587940, contextName, $namespace, releaseName, revision, opts);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @param {$models.HelmTestOpts} opts
 * @returns {$CancellablePromise<helm$0.TestResult>}
 */
export function Test(contextName, $namespace, releaseName, opts) {
    return $Call.ByID(742184180, contextName, $namespace, releaseName, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} releaseName
 * @param {$models.HelmUninstallOpts} opts
 * @returns {$CancellablePromise<void>}
 */
export function Uninstall(contextName, $namespace, releaseName, opts) {
    return $Call.ByID(4281748658, contextName, $namespace, releaseName, opts);
}

// Private type creation functions
const $$createType0 = helm$0.RevisionDiff.createFrom;
const $$createType1 = helm$0.Revision.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = helm$0.Hook.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = helm$0.OwnedRef.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.HelmPermissions.createFrom;
const $$createType8 = helm$0.TestResult.createFrom;
