// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AppService from "./appservice.js";
import * as ClusterService from "./clusterservice.js";
import * as ConfigService from "./configservice.js";
import * as DrainService from "./drainservice.js";
import * as ExecService from "./execservice.js";
import * as LogService from "./logservice.js";
import * as MetricsService from "./metricsservice.js";
import * as PluginService from "./pluginservice.js";
import * as PortForwardService from "./portforwardservice.js";
import * as ResourceService from "./resourceservice.js";
import * as SchemaService from "./schemaservice.js";
export {
    AppService,
    ClusterService,
    ConfigService,
    DrainService,
    ExecService,
    LogService,
    MetricsService,
    PluginService,
    PortForwardService,
    ResourceService,
    SchemaService
};

export {
    RolloutRevision
} from "./models.js";
