// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logs$0 from "../logs/models.js";

/**
 * @param {string} ctxName
 * @param {string} ns
 * @param {string} podName
 * @param {logs$0.LogOptions} opts
 * @returns {$CancellablePromise<string>}
 */
export function StartLogStream(ctxName, ns, podName, opts) {
    return $Call.ByID(475158610, ctxName, ns, podName, opts);
}

/**
 * @param {string} streamID
 * @returns {$CancellablePromise<void>}
 */
export function StopLogStream(streamID) {
    return $Call.ByID(1299866654, streamID);
}
