// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metrics$0 from "../metrics/models.js";

/**
 * @param {string} clusterCtx
 * @returns {$CancellablePromise<metrics$0.MetricsCapability>}
 */
export function GetCapabilities(clusterCtx) {
    return $Call.ByID(719665459, clusterCtx).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} clusterCtx
 * @param {string} gvr
 * @param {string} $namespace
 * @returns {$CancellablePromise<{ [_ in string]?: metrics$0.MetricResult[] }>}
 */
export function GetListMetrics(clusterCtx, gvr, $namespace) {
    return $Call.ByID(496327662, clusterCtx, gvr, $namespace).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} clusterCtx
 * @param {string} $namespace
 * @param {number} rangeMinutes
 * @returns {$CancellablePromise<metrics$0.MetricsResponse | null>}
 */
export function GetNamespaceMetrics(clusterCtx, $namespace, rangeMinutes) {
    return $Call.ByID(2982105593, clusterCtx, $namespace, rangeMinutes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} clusterCtx
 * @param {string} gvr
 * @param {string} $namespace
 * @param {string} name
 * @param {number} rangeMinutes
 * @returns {$CancellablePromise<{ [_ in string]?: metrics$0.MetricResult[] }>}
 */
export function GetPluginMetrics(clusterCtx, gvr, $namespace, name, rangeMinutes) {
    return $Call.ByID(1491496035, clusterCtx, gvr, $namespace, name, rangeMinutes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} clusterCtx
 * @param {string} gvr
 * @param {string} $namespace
 * @param {string} name
 * @param {number} rangeMinutes
 * @returns {$CancellablePromise<metrics$0.MetricsResponse | null>}
 */
export function GetResourceMetrics(clusterCtx, gvr, $namespace, name, rangeMinutes) {
    return $Call.ByID(90947346, clusterCtx, gvr, $namespace, name, rangeMinutes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} clusterCtx
 * @returns {$CancellablePromise<metrics$0.MetricsCapability | null>}
 */
export function RedetectSources(clusterCtx) {
    return $Call.ByID(169399461, clusterCtx).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} clusterCtx
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function SetPrometheusEndpoint(clusterCtx, url) {
    return $Call.ByID(1645142504, clusterCtx, url);
}

// Private type creation functions
const $$createType0 = metrics$0.MetricsCapability.createFrom;
const $$createType1 = metrics$0.MetricResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = metrics$0.MetricsResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Nullable($$createType0);
