// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PluginService {

    /** Creates a new PluginService instance. */
    constructor($$source: Partial<PluginService> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginService instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginService($$parsedSource as Partial<PluginService>);
    }
}

export class RolloutRevision {
    "revision": number;
    "name": string;
    "labels"?: { [_ in string]?: any };

    /** Creates a new RolloutRevision instance. */
    constructor($$source: Partial<RolloutRevision> = {}) {
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RolloutRevision instance from a string or object.
     */
    static createFrom($$source: any = {}): RolloutRevision {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField2_0($$parsedSource["labels"]);
        }
        return new RolloutRevision($$parsedSource as Partial<RolloutRevision>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
