// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RolloutRevision {
    /**
     * Creates a new RolloutRevision instance.
     * @param {Partial<RolloutRevision>} [$$source = {}] - The source object to create the RolloutRevision.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["labels"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RolloutRevision instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RolloutRevision}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField2_0($$parsedSource["labels"]);
        }
        return new RolloutRevision(/** @type {Partial<RolloutRevision>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
