// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "../plugin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resource$0 from "../resource/models.js";

/**
 * AddInsecureRegistry appends host to the InsecureRegistries config list (no-op if already present).
 * @param {string} host
 * @returns {$CancellablePromise<void>}
 */
export function AddInsecureRegistry(host) {
    return $Call.ByID(2550531315, host);
}

/**
 * DeletePluginStorageKey deletes a storage key for the named plugin.
 * @param {string} pluginName
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DeletePluginStorageKey(pluginName, key) {
    return $Call.ByID(2741694887, pluginName, key);
}

/**
 * DisablePlugin deactivates a plugin without removing its registry entry.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DisablePlugin(name) {
    return $Call.ByID(2827133906, name);
}

/**
 * EmitClusterEvent notifies all active plugins with events permission about a cluster event.
 * Also emits a Wails "plugin:event" event so frontend plugin components can subscribe.
 * @param {string} eventName
 * @param {string} payload
 * @returns {$CancellablePromise<void>}
 */
export function EmitClusterEvent(eventName, payload) {
    return $Call.ByID(2846539646, eventName, payload);
}

/**
 * EnablePlugin reloads a disabled plugin's runtime and re-registers its extension points.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function EnablePlugin(name) {
    return $Call.ByID(3372152903, name);
}

/**
 * @returns {$CancellablePromise<plugin$0.CommandEntry[]>}
 */
export function GetPluginCommands() {
    return $Call.ByID(2652726328).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} gvr
 * @returns {$CancellablePromise<plugin$0.ContextMenuEntry[]>}
 */
export function GetPluginContextMenuItems(gvr) {
    return $Call.ByID(52700694, gvr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<(resource$0.Descriptor | null)[]>}
 */
export function GetPluginDescriptors() {
    return $Call.ByID(708743124).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<plugin$0.DetailTabEntry[]>}
 */
export function GetPluginDetailTabs() {
    return $Call.ByID(1861103043).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<plugin$0.HeaderWidgetEntry[]>}
 */
export function GetPluginHeaderWidgets() {
    return $Call.ByID(1768483840).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} gvr
 * @returns {$CancellablePromise<plugin$0.ListColumnEntry[]>}
 */
export function GetPluginListColumns(gvr) {
    return $Call.ByID(2256052701, gvr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} gvr
 * @returns {$CancellablePromise<plugin$0.OverviewFieldEntry[]>}
 */
export function GetPluginOverviewFields(gvr) {
    return $Call.ByID(3013906384, gvr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<plugin$0.SidebarEntry[]>}
 */
export function GetPluginSidebarEntries() {
    return $Call.ByID(3696952998).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<plugin$0.StatusBarEntry[]>}
 */
export function GetPluginStatusBarWidgets() {
    return $Call.ByID(2691181182).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetPluginStorageKey returns a storage value for the named plugin.
 * @param {string} pluginName
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetPluginStorageKey(pluginName, key) {
    return $Call.ByID(3107711926, pluginName, key);
}

/**
 * InstallPlugin installs a plugin from an OCI reference (oci://...), a directory path,
 * or an OCI archive (.oci.tar / .oci.tar.gz). After installation, loads the plugin and
 * emits plugins:loaded.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function InstallPlugin(path) {
    return $Call.ByID(45558949, path);
}

/**
 * ListPluginStorageKeys returns all storage keys for the named plugin.
 * @param {string} pluginName
 * @returns {$CancellablePromise<string[]>}
 */
export function ListPluginStorageKeys(pluginName) {
    return $Call.ByID(246306153, pluginName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @returns {$CancellablePromise<plugin$0.PluginInfo[]>}
 */
export function ListPlugins() {
    return $Call.ByID(2936986561).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * PackPlugin packs a plugin directory into an OCI tar.gz archive.
 * Returns the path to the generated archive.
 * @param {string} pluginDir
 * @returns {$CancellablePromise<string>}
 */
export function PackPlugin(pluginDir) {
    return $Call.ByID(1780293953, pluginDir);
}

/**
 * ReloadPlugin performs a full unload-then-reload cycle for the named plugin.
 * Called by the PluginWatcher on file changes.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ReloadPlugin(name) {
    return $Call.ByID(2066653501, name);
}

/**
 * ReloadPluginManual is the Wails-bound version of ReloadPlugin.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ReloadPluginManual(name) {
    return $Call.ByID(1045275339, name);
}

/**
 * SaveRegistryCredentials persists credentials for an OCI registry host to ~/.docker/config.json.
 * @param {string} host
 * @param {string} username
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function SaveRegistryCredentials(host, username, password) {
    return $Call.ByID(1007465601, host, username, password);
}

/**
 * SetPluginStorageKey sets a storage value for the named plugin.
 * @param {string} pluginName
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetPluginStorageKey(pluginName, key, value) {
    return $Call.ByID(2619222610, pluginName, key, value);
}

/**
 * UninstallPlugin removes the plugin directory and all associated data.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UninstallPlugin(name) {
    return $Call.ByID(2836258476, name);
}

// Private type creation functions
const $$createType0 = plugin$0.CommandEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = plugin$0.ContextMenuEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = resource$0.Descriptor.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = plugin$0.DetailTabEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = plugin$0.HeaderWidgetEntry.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = plugin$0.ListColumnEntry.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = plugin$0.OverviewFieldEntry.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = plugin$0.SidebarEntry.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = plugin$0.StatusBarEntry.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($Create.Any);
const $$createType20 = plugin$0.PluginInfo.createFrom;
const $$createType21 = $Create.Array($$createType20);
