// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as portforward$0 from "../portforward/models.js";

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<portforward$0.ForwardSpec[]>}
 */
export function ListForwards(contextName) {
    return $Call.ByID(4274792300, contextName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {portforward$0.TargetKind} targetKind
 * @param {string} targetName
 * @param {string} targetGVR
 * @param {number} localPort
 * @param {number} remotePort
 * @returns {$CancellablePromise<portforward$0.ForwardSpec>}
 */
export function StartForward(contextName, $namespace, targetKind, targetName, targetGVR, localPort, remotePort) {
    return $Call.ByID(2691853059, contextName, $namespace, targetKind, targetName, targetGVR, localPort, remotePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} forwardID
 * @returns {$CancellablePromise<void>}
 */
export function StopForward(forwardID) {
    return $Call.ByID(465318475, forwardID);
}

// Private type creation functions
const $$createType0 = portforward$0.ForwardSpec.createFrom;
const $$createType1 = $Create.Array($$createType0);
