// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as portforward$0 from "../portforward/models.js";

export function ListForwards(contextName: string): $CancellablePromise<portforward$0.ForwardSpec[]> {
    return $Call.ByID(4274792300, contextName).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartForward(contextName: string, $namespace: string, targetKind: portforward$0.TargetKind, targetName: string, targetGVR: string, localPort: number, remotePort: number): $CancellablePromise<portforward$0.ForwardSpec> {
    return $Call.ByID(2691853059, contextName, $namespace, targetKind, targetName, targetGVR, localPort, remotePort).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StopForward(forwardID: string): $CancellablePromise<void> {
    return $Call.ByID(465318475, forwardID);
}

// Private type creation functions
const $$createType0 = portforward$0.ForwardSpec.createFrom;
const $$createType1 = $Create.Array($$createType0);
