// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as portforward$0 from "../portforward/models.js";

/**
 * ConnectSavedForward starts a saved forward using its existing ID so it
 * doesn't create a duplicate saved entry.
 * @param {string} ctxName
 * @param {string} savedID
 * @returns {$CancellablePromise<portforward$0.ForwardSpec>}
 */
export function ConnectSavedForward(ctxName, savedID) {
    return $Call.ByID(646437684, ctxName, savedID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<portforward$0.ForwardSpec[]>}
 */
export function ListForwards(contextName) {
    return $Call.ByID(4274792300, contextName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} ctxName
 * @returns {$CancellablePromise<config$0.SavedPortForward[]>}
 */
export function ListSavedPortForwards(ctxName) {
    return $Call.ByID(2424660924, ctxName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} ctxName
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveSavedPortForward(ctxName, id) {
    return $Call.ByID(1339133687, ctxName, id);
}

/**
 * @param {string} ctxName
 * @param {config$0.SavedPortForward} fwd
 * @returns {$CancellablePromise<void>}
 */
export function SavePortForward(ctxName, fwd) {
    return $Call.ByID(334273145, ctxName, fwd);
}

/**
 * @param {string} ctxName
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetPortForwardEnabled(ctxName, id, enabled) {
    return $Call.ByID(1617244075, ctxName, id, enabled);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {portforward$0.TargetKind} targetKind
 * @param {string} targetName
 * @param {string} targetGVR
 * @param {number} localPort
 * @param {number} remotePort
 * @returns {$CancellablePromise<portforward$0.ForwardSpec>}
 */
export function StartForward(contextName, $namespace, targetKind, targetName, targetGVR, localPort, remotePort) {
    return $Call.ByID(2691853059, contextName, $namespace, targetKind, targetName, targetGVR, localPort, remotePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} forwardID
 * @returns {$CancellablePromise<void>}
 */
export function StopForward(forwardID) {
    return $Call.ByID(465318475, forwardID);
}

// Private type creation functions
const $$createType0 = portforward$0.ForwardSpec.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = config$0.SavedPortForward.createFrom;
const $$createType3 = $Create.Array($$createType2);
