// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cluster$0 from "../cluster/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resource$0 from "../resource/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as watcher$0 from "../watcher/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @param {{ [_ in string]?: any }} obj
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function CreateResource(contextName, gvr, $namespace, obj) {
    return $Call.ByID(1901610632, contextName, gvr, $namespace, obj).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteJobCascade(contextName, $namespace, name) {
    return $Call.ByID(2160112924, contextName, $namespace, name);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteJobOrphan(contextName, $namespace, name) {
    return $Call.ByID(762631980, contextName, $namespace, name);
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteResource(contextName, gvr, $namespace, name) {
    return $Call.ByID(1205855719, contextName, gvr, $namespace, name);
}

/**
 * @returns {$CancellablePromise<resource$0.ResourceEngine | null>}
 */
export function Engine() {
    return $Call.ByID(2725305666).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<resource$0.EnricherRegistry | null>}
 */
export function EnricherRegistry() {
    return $Call.ByID(2852732061).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} name
 * @param {string} newSize
 * @returns {$CancellablePromise<void>}
 */
export function ExpandPVC(contextName, $namespace, name, newSize) {
    return $Call.ByID(1652489051, contextName, $namespace, name, newSize);
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ForceDeleteResource(contextName, gvr, $namespace, name) {
    return $Call.ByID(1634363412, contextName, gvr, $namespace, name);
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAllTemplateGVRs(contextName) {
    return $Call.ByID(1012417887, contextName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<(resource$0.Descriptor | null)[]>}
 */
export function GetDescriptors() {
    return $Call.ByID(2292983530).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} uid
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetEvents(contextName, $namespace, uid) {
    return $Call.ByID(3708386421, contextName, $namespace, uid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetResource(contextName, gvr, $namespace, name) {
    return $Call.ByID(135959152, contextName, gvr, $namespace, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<$models.RolloutRevision[]>}
 */
export function GetRolloutHistory(contextName, gvr, $namespace, name) {
    return $Call.ByID(2359955171, contextName, gvr, $namespace, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @returns {$CancellablePromise<resource$0.Template[]>}
 */
export function GetTemplates(contextName, gvr) {
    return $Call.ByID(1548246975, contextName, gvr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<cluster$0.APIResource[]>}
 */
export function ListAPIResources(contextName) {
    return $Call.ByID(1259308621, contextName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function ListResources(contextName, gvr, $namespace) {
    return $Call.ByID(3351008733, contextName, gvr, $namespace).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function PauseRollout(contextName, $namespace, name) {
    return $Call.ByID(1279088551, contextName, $namespace, name);
}

/**
 * @returns {$CancellablePromise<resource$0.Registry | null>}
 */
export function Registry() {
    return $Call.ByID(3098448631).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RestartResource(contextName, gvr, $namespace, name) {
    return $Call.ByID(1778604759, contextName, gvr, $namespace, name);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ResumeCronJob(contextName, $namespace, name) {
    return $Call.ByID(3937380918, contextName, $namespace, name);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ResumeRollout(contextName, $namespace, name) {
    return $Call.ByID(3072590784, contextName, $namespace, name);
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @param {string} name
 * @param {number} revision
 * @returns {$CancellablePromise<void>}
 */
export function RollbackToRevision(contextName, gvr, $namespace, name, revision) {
    return $Call.ByID(61840640, contextName, gvr, $namespace, name, revision);
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @param {string} name
 * @param {number} replicas
 * @returns {$CancellablePromise<void>}
 */
export function ScaleResource(contextName, gvr, $namespace, name, replicas) {
    return $Call.ByID(1670858778, contextName, gvr, $namespace, name, replicas);
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @returns {$CancellablePromise<void>}
 */
export function StartWatch(contextName, gvr, $namespace) {
    return $Call.ByID(3194488095, contextName, gvr, $namespace);
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @returns {$CancellablePromise<void>}
 */
export function StopWatch(contextName, gvr, $namespace) {
    return $Call.ByID(1152083571, contextName, gvr, $namespace);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SuspendCronJob(contextName, $namespace, name) {
    return $Call.ByID(541678507, contextName, $namespace, name);
}

/**
 * @param {string} contextName
 * @param {string} $namespace
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function TriggerCronJob(contextName, $namespace, name) {
    return $Call.ByID(2347619787, contextName, $namespace, name);
}

/**
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} $namespace
 * @param {{ [_ in string]?: any }} obj
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function UpdateResource(contextName, gvr, $namespace, obj) {
    return $Call.ByID(2032718897, contextName, gvr, $namespace, obj).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<watcher$0.WatchManager | null>}
 */
export function WatchMgr() {
    return $Call.ByID(1932566071).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = resource$0.ResourceEngine.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = resource$0.EnricherRegistry.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = resource$0.Descriptor.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType0);
const $$createType10 = $models.RolloutRevision.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = resource$0.Template.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = cluster$0.APIResource.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = resource$0.Registry.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = watcher$0.WatchManager.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
