// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetSchema returns the JSON Schema for the given GVR, extracted from the cluster's OpenAPI v3 spec.
 * The schema is cached to disk keyed by server URL + server version to survive restarts.
 * kind must be the PascalCase resource Kind (e.g. "Deployment") used to locate the schema in OpenAPI.
 * @param {string} contextName
 * @param {string} gvr
 * @param {string} kind
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetSchema(contextName, gvr, kind) {
    return $Call.ByID(2694404114, contextName, gvr, kind).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
