// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @param {string} tabID
 * @returns {$CancellablePromise<void>}
 */
export function AttachTab(id, tabID) {
    return $Call.ByID(3734750756, id, tabID);
}

/**
 * CleanupOrphans deletes all pvc-browser pods in the given context that are
 * not owned by the current session.
 * @param {string} contextName
 * @returns {$CancellablePromise<void>}
 */
export function CleanupOrphans(contextName) {
    return $Call.ByID(586032643, contextName);
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<$models.ManagedPodDTO[]>}
 */
export function ListManaged(contextName) {
    return $Call.ByID(3272821081, contextName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Replace stops the pod referenced by id (if any) and spawns a new one.
 * Used when the user changes overrides for an already-attached browser pod.
 * @param {string} id
 * @param {$models.SpawnRequestDTO} req
 * @returns {$CancellablePromise<$models.SpawnResult>}
 */
export function Replace(id, req) {
    return $Call.ByID(109702944, id, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} contextName
 * @returns {$CancellablePromise<$models.OrphanPodDTO[]>}
 */
export function ScanOrphans(contextName) {
    return $Call.ByID(4284101324, contextName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.SpawnRequestDTO} req
 * @returns {$CancellablePromise<$models.SpawnResult>}
 */
export function Spawn(req) {
    return $Call.ByID(819807927, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Stop(id) {
    return $Call.ByID(42006192, id);
}

/**
 * TriggerOrphanScan runs the scan and applies the OrphanCleanupOnStartup
 * dispatch (auto/prompt/ignore) synchronously, returning the orphan list for
 * prompt mode. For ignore or after-auto-cleanup it returns an empty slice.
 * Used by the frontend on-mount pull path to avoid races against the
 * OnClusterConnected event.
 * @param {string} contextName
 * @returns {$CancellablePromise<$models.OrphanPodDTO[]>}
 */
export function TriggerOrphanScan(contextName) {
    return $Call.ByID(1082977015, contextName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ManagedPodDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SpawnResult.createFrom;
const $$createType3 = $models.OrphanPodDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
