# name: Docker Registry Secret
# description: Image pull secret for private registries
apiVersion: v1
kind: Secret
metadata:
  name: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
